name: "Snapshot"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  APPLICATION_NAME: ImageEditor

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      APPNAME: ${{ steps.get_appname.outputs.APPNAME }}
      VERSION: ${{ steps.get_version.outputs.VERSION }}
    steps:
    - name: get-appname
      id: get_appname
      run: echo ::set-output name=APPNAME::${APPLICATION_NAME}
    - name: get-version
      id: get_version
      run: echo "VERSION=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"


  windows:
    needs: [setup]
    runs-on: windows-latest
    env:
      PACKAGENAME: ${{ needs.setup.outputs.APPNAME }}-${{ needs.setup.outputs.VERSION }}-windows
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy pillow pyside6
        pip install pyinstaller pyinstaller-versionfile
    - name: build
      run: |
        pyinstaller image-editor.spec
    - name: package
      run: |
        cd dist
        dir ImageEditor
        7z a -r ${{ env.PACKAGENAME }}.zip ImageEditor
        move ${{ env.PACKAGENAME }}.zip ..
        cd ..
    - name: upload
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.PACKAGENAME }}
        path: ${{ env.PACKAGENAME }}.zip
