name: "Release"

on:
  push:
    tags:
      - '*'

jobs:
  version:
    name: Version
    uses: ./.github/workflows/job_version.yml

  title:
    needs: version
    name: Title
    runs-on: ubuntu-latest
    outputs:
      PACKAGENAME: ${{ needs.version.outputs.APPNAME }}-${{ needs.version.outputs.VERSION }}
      APPNAME: ${{ needs.version.outputs.APPNAME }}
    steps:
      - run: "true"

  windows:
    needs: [version, title]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install pyinstaller pyinstaller-versionfile
    - name: Create versionfile
      run: |
        touch metadata.yml
        echo "FileDescription: ${{ needs.title.outputs.APPNAME }}" >> metadata.yml
        echo "InternalName: ${{ needs.title.outputs.APPNAME }}" >> metadata.yml
        create-version-file metadata.yml --outfile versionfile.txt --version ${{ needs.version.outputs.VERSION }}
    - name: build
      run: |
        SET PYTHONOPTIMIZE=1
        pyinstaller image-editor.spec
    - name: package
      run: |
        cd dist
        dir ${{ needs.title.outputs.APPNAME }}
        7z a -r ${{ needs.title.outputs.PACKAGENAME }}.zip ${{ needs.title.outputs.APPNAME }}
        move ${{ needs.title.outputs.PACKAGENAME }}.zip ..
        cd ..
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ needs.title.outputs.PACKAGENAME }}
        path: ${{ needs.title.outputs.PACKAGENAME }}.zip
        #if-no-files-found: error

  release:
    name: Create release
    needs: [title, windows]
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    - name: release
      id: release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: Version ${{ github.ref }}
    - name: upload
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: artifacts/${{ needs.title.outputs.PACKAGENAME }}/${{ needs.title.outputs.PACKAGENAME }}.zip
        asset_name: ${{ needs.title.outputs.PACKAGENAME }}.zip
        asset_content_type: application/zip
