name: "Build resources"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  resources:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - uses: actions/setup-python@v3
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pyside6
    - name: Build resources
      run: |
        python misc/ts2qm.py
        python misc/qrc2py.py
