name: "Snapshot"

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'src/i18n/*'
      - 'src/icons/*'
      - 'src/resources.qrc'
#  pull_request:
#    branches: [ "main" ]

#permissions:
#  contents: read

env:
  APPLICATION_NAME: ImageEditor

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      APPNAME: ${{ steps.get_appname.outputs.APPNAME }}
      VERSION: ${{ steps.get_version.outputs.VERSION }}
      REVISION: ${{ steps.get_revision.outputs.REVISION }}
    steps:
    - uses: actions/checkout@v3
    - name: get-appname
      id: get_appname
      run: echo "APPNAME=${APPLICATION_NAME}" >> "$GITHUB_OUTPUT"
    - name: get-version
      id: get_version
      run: echo "VERSION=$(python -c 'from src import __version__; print(__version__)')" >> "$GITHUB_OUTPUT"
    - name: get-revision
      id: get_revision
      run: echo "REVISION=${{ github.run_number }}" >> "$GITHUB_OUTPUT"

  windows:
    needs: [setup]
    runs-on: windows-latest
    env:
      PACKAGENAME: ${{ needs.setup.outputs.APPNAME }}-${{ needs.setup.outputs.VERSION }}-${{ needs.setup.outputs.REVISION }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - uses: actions/setup-python@v3
      with:
        python-version: '3.12'
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install -r requirements-dev.txt
    - name: Create versionfile
      run: |
        echo "FileDescription: ${{ needs.setup.outputs.APPNAME }}" > metadata.yml
        echo "InternalName: ${{ needs.setup.outputs.APPNAME }}" >> metadata.yml
        create-version-file metadata.yml --outfile versionfile.txt --version ${{ needs.setup.outputs.VERSION }}.0.${{ needs.setup.outputs.REVISION }}
    - name: build
      run: |
        SET PYTHONOPTIMIZE=1
        pyinstaller image-editor.spec
    - name: package
      run: |
        cd dist
        dir ImageEditor
        7z a -r ${{ env.PACKAGENAME }}.zip ImageEditor
        move ${{ env.PACKAGENAME }}.zip ..
        cd ..
    - name: upload
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PACKAGENAME }}
        path: ${{ env.PACKAGENAME }}.zip
        #if-no-files-found: error

  prerelease:
    name: Create pre-release
    needs: [setup, windows]
    runs-on: ubuntu-latest
    env:
      PACKAGENAME: ${{ needs.setup.outputs.APPNAME }}-${{ needs.setup.outputs.VERSION }}-${{ needs.setup.outputs.REVISION }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        path: artifacts
    - name: release
      id: release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
    - name: upload
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: artifacts/${{ env.PACKAGENAME }}/${{ env.PACKAGENAME }}.zip
        asset_name: ${{ env.PACKAGENAME }}.zip
        asset_content_type: application/zip
